export const CITIES_BY_REGION = {
    Andalucía: [
      'Sevilla',
      'Málaga',
      'Córdoba',
      'Granada',
      'Jaén',
      'Almería',
      'Huelva',
      'Cádiz',
      'Jerez de la Frontera',
      'Marbella',
      'Algeciras',
      'Dos Hermanas',
      'Écija',
    ],
    Aragón: [
      'Zaragoza',
      'Huesca',
      'Teruel',
      'Calatayud',
      'Ejea de los Caballeros',
      'Barbastro',
    ],
    Asturias: ['Oviedo', 'Gijón', 'Avilés', 'Mieres', 'Langreo'],
    Islas_Baleares: [
      'Palma de Mallorca',
      'Ibiza',
      'Mahón',
      'Ciutadella de Menorca',
      'Inca',
    ],
    Canarias: [
      'Las Palmas de Gran Canaria',
      'Santa Cruz de Tenerife',
      'San Cristóbal de La Laguna',
      'Telde',
      'Arona',
    ],
    Cantabria: ['Santander', 'Torrelavega', 'Castro-Urdiales', 'Laredo'],
    Castilla_y_León: [
      'Valladolid',
      'Burgos',
      'León',
      'Salamanca',
      'Segovia',
      'Soria',
      'Ávila',
      'Palencia',
      'Zamora',
      'Ponferrada',
      'Aranda de Duero',
      'Medina del Campo',
    ],
    Castilla_La_Mancha: [
      'Toledo',
      'Albacete',
      'Ciudad Real',
      'Cuenca',
      'Guadalajara',
      'Talavera de la Reina',
      'Puertollano',
      'Hellín',
    ],
    Cataluña: [
      'Barcelona',
      'Lleida',
      'Girona',
      'Tarragona',
      'Hospitalet de Llobregat',
      'Badalona',
      'Sabadell',
      'Terrassa',
    ],
    Comunidad_Valenciana: [
      'Valencia',
      'Alicante',
      'Castellón de la Plana',
      'Elche',
      'Torrevieja',
      'Orihuela',
      'Gandía',
    ],
    Extremadura: [
      'Mérida',
      'Badajoz',
      'Cáceres',
      'Plasencia',
      'Don Benito',
      'Almendralejo',
      'Villanueva de la Serena',
    ],
    Galicia: [
      'Santiago de Compostela',
      'Vigo',
      'A Coruña',
      'Ourense',
      'Lugo',
      'Pontevedra',
      'Ferrol',
      'Oleiros',
    ],
    Madrid: ['Madrid', 'Alcalá de Henares', 'Leganés', 'Getafe', 'Móstoles'],
    Murcia: ['Murcia', 'Cartagena', 'Lorca', 'Molina de Segura', 'Alcantarilla'],
    Navarra: ['Pamplona', 'Tudela', 'Barañáin', 'Burlada', 'Estella'],
    País_Vasco: [
      'Bilbao',
      'Vitoria-Gasteiz',
      'San Sebastián',
      'Barakaldo',
      'Getxo',
    ],
    La_Rioja: ['Logroño', 'Calahorra', 'Arnedo', 'Haro', 'Alfaro'],
    Ceuta: ['Ceuta'],
    Melilla: ['Melilla'],
  };